### PR TITLE
Update badges

### PR DESCRIPTION
**Pull request by MeltySnow**
@nottrobin asked me to update badges to make them more consistent.

## Done

Added CircleCI and code coverage badges to the README.

### CODE REVIEW

**Comment by barrymcgee** [comment]
@MeltySnow The CircleCI badge seems to fail to load?

Screenshot 2019-07-17 at 19 45 02

**Review by barrymcgee — CHANGES_REQUESTED** [review]
QA error, see comment above.

**Comment by cristinadresch** [comment]
Code is on shopify. Closing this issue now.

**Comment by nottrobin** [comment]
Can someone clarify what @cristinadresch means by "code is on shopify"? Is it that this repository is not used? Should it be retired? @tbille, @jpmartinspt?

**Pull request closed without merging**
